// src/constants/automationConstants.js

export const AUTOMATION_TYPES = {
  BOOKING_REMINDER: "BOOKING_REMINDER",
  MEMBERSHIP_EXPIRY_REMINDER: "MEMBERSHIP_EXPIRY_REMINDER",
  PAYMENT_NOTIFICATION: "PAYMENT_NOTIFICATION",
  INVOICE_GENERATION: "INVOICE_GENERATION",
  DAILY_REPORT: "DAILY_REPORT",
  CUSTOM: "CUSTOM"
};


export const AUTOMATION_TRIGGER_TYPES = {
  SCHEDULED_DATE_TIME: "SCHEDULED_DATE_TIME",
  MEMBERSHIP_EXPIRING: "MEMBERSHIP_EXPIRING",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS"
};


export const AUTOMATION_ACTION_TYPES = {
  SEND_NOTIFICATION: "SEND_NOTIFICATION"
};


export const AUTOMATION_RECIPIENTS = {
  TRIGGER_MEMBER: "TRIGGER_MEMBER",
  LIBRARY_OWNER: "LIBRARY_OWNER"
};


export const AUTOMATION_CONDITION_FIELDS = {
  MEMBERSHIP_PLAN_ID: "MEMBERSHIP_PLAN_ID",
  MEMBERSHIP_STATUS: "MEMBERSHIP_STATUS",
  DAYS_UNTIL_EXPIRY: "DAYS_UNTIL_EXPIRY",
  PAYMENT_AMOUNT: "PAYMENT_AMOUNT",
  PAYMENT_STATUS: "PAYMENT_STATUS",
  PAYMENT_METHOD: "PAYMENT_METHOD",
  MEMBER_ID: "MEMBER_ID"
};


export const AUTOMATION_CONDITION_OPERATORS = {
  EQUALS: "EQUALS",
  NOT_EQUALS: "NOT_EQUALS",
  GREATER_THAN: "GREATER_THAN",
  GREATER_THAN_OR_EQUAL: "GREATER_THAN_OR_EQUAL",
  LESS_THAN: "LESS_THAN",
  LESS_THAN_OR_EQUAL: "LESS_THAN_OR_EQUAL",
  CONTAINS: "CONTAINS",
  IN: "IN"
};


export const AUTOMATION_EXECUTION_STATUS = {
  PROCESSING: "PROCESSING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED"
};