const couponMockData = [
    {
        id: 1,
        code: "WELCOME50",
        description: "Welcome offer for new students",
        discountType: "PERCENTAGE",
        discountValue: 50,
        minimumAmount: 500,
        maximumDiscount: 250,
        validFrom: "2026-09-01",
        validUntil: "2026-10-31",
        status: "ACTIVE",
        createdAt: "2026-09-01",
        usedAt: null,
        usedBy: null,
    },
    {
        id: 2,
        code: "SAVE100",
        description: "Flat discount on qualifying bookings",
        discountType: "FIXED_AMOUNT",
        discountValue: 100,
        minimumAmount: 800,
        maximumDiscount: null,
        validFrom: "2026-09-10",
        validUntil: "2026-11-30",
        status: "ACTIVE",
        createdAt: "2026-09-10",
        usedAt: null,
        usedBy: null,
    },
    {
        id: 3,
        code: "STUDY20",
        description: "Student study booking offer",
        discountType: "PERCENTAGE",
        discountValue: 20,
        minimumAmount: 500,
        maximumDiscount: 200,
        validFrom: "2026-08-01",
        validUntil: "2026-09-30",
        status: "USED",
        createdAt: "2026-08-01",
        usedAt: "2026-09-20 14:32",
        usedBy: "Rahul Sharma",
    },
    {
        id: 4,
        code: "NEWYEAR500",
        description: "New year promotional offer",
        discountType: "FIXED_AMOUNT",
        discountValue: 500,
        minimumAmount: 2000,
        maximumDiscount: null,
        validFrom: "2026-01-01",
        validUntil: "2026-01-31",
        status: "EXPIRED",
        createdAt: "2026-01-01",
        usedAt: null,
        usedBy: null,
    },
    {
        id: 5,
        code: "LIBRARY10",
        description: "Special library promotion",
        discountType: "PERCENTAGE",
        discountValue: 10,
        minimumAmount: 500,
        maximumDiscount: 100,
        validFrom: "2026-09-01",
        validUntil: "2026-12-31",
        status: "DEACTIVATED",
        createdAt: "2026-09-01",
        usedAt: null,
        usedBy: null,
    },
];

export default couponMockData;